package Shapes.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCanvas = createDescriptorForCanvas();
  /*package*/ final ConceptDescriptor myConceptCircle = createDescriptorForCircle();
  /*package*/ final ConceptDescriptor myConceptShape = createDescriptorForShape();
  /*package*/ final ConceptDescriptor myConceptSquare = createDescriptorForSquare();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, "jetbrains.mps.execution.util");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCanvas, myConceptCircle, myConceptShape, myConceptSquare);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Canvas:
        return myConceptCanvas;
      case LanguageConceptSwitch.Circle:
        return myConceptCircle;
      case LanguageConceptSwitch.Shape:
        return myConceptShape;
      case LanguageConceptSwitch.Square:
        return myConceptSquare;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCanvas() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Canvas", 0xe5eac66b29504d53L, 0x84e4251b08c5a5c1L, 0x2b4ef0b60a235e35L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:8cf8ee6b-8cde-4d0a-b5c8-d5909acd0eac(Shapes.structure)/3120696256459136565");
    b.version(3);
    b.aggregate("shapes", 0x2b4ef0b60a235e38L).target(0xe5eac66b29504d53L, 0x84e4251b08c5a5c1L, 0x2b4ef0b60a235e25L).optional(true).ordered(true).multiple(true).origin("3120696256459136568").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCircle() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Circle", 0xe5eac66b29504d53L, 0x84e4251b08c5a5c1L, 0x2b4ef0b60a235e29L);
    b.class_(false, false, false);
    // extends: Shapes.structure.Shape
    b.super_(0xe5eac66b29504d53L, 0x84e4251b08c5a5c1L, 0x2b4ef0b60a235e25L);
    b.origin("r:8cf8ee6b-8cde-4d0a-b5c8-d5909acd0eac(Shapes.structure)/3120696256459136553");
    b.version(3);
    b.property("x", 0x2b4ef0b60a235e2dL).type(PrimitiveTypeId.INTEGER).origin("3120696256459136557").done();
    b.property("y", 0x2b4ef0b60a235e2eL).type(PrimitiveTypeId.INTEGER).origin("3120696256459136558").done();
    b.property("radius", 0x2b4ef0b60a235e2fL).type(PrimitiveTypeId.INTEGER).origin("3120696256459136559").done();
    b.alias("circle");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForShape() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Shape", 0xe5eac66b29504d53L, 0x84e4251b08c5a5c1L, 0x2b4ef0b60a235e25L);
    b.class_(false, true, false);
    b.origin("r:8cf8ee6b-8cde-4d0a-b5c8-d5909acd0eac(Shapes.structure)/3120696256459136549");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSquare() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Square", 0xe5eac66b29504d53L, 0x84e4251b08c5a5c1L, 0x2b4ef0b60a235e31L);
    b.class_(false, false, false);
    // extends: Shapes.structure.Shape
    b.super_(0xe5eac66b29504d53L, 0x84e4251b08c5a5c1L, 0x2b4ef0b60a235e25L);
    b.origin("r:8cf8ee6b-8cde-4d0a-b5c8-d5909acd0eac(Shapes.structure)/3120696256459136561");
    b.version(3);
    b.property("upperLeftX", 0x2b4ef0b60a235e32L).type(PrimitiveTypeId.INTEGER).origin("3120696256459136562").done();
    b.property("upperLeftY", 0x2b4ef0b60a235e33L).type(PrimitiveTypeId.INTEGER).origin("3120696256459136563").done();
    b.property("size", 0x2b4ef0b60a235e34L).type(PrimitiveTypeId.INTEGER).origin("3120696256459136564").done();
    b.alias("square");
    return b.create();
  }
}
